<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $nombre
 * @property string $apellido
 * @property string $cedula
 * @property string $role
 * @property Doctrine_Collection $Doctor
 * @property Doctrine_Collection $Paciente
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getUsername() Returns the current record's "username" value
 * @method string              getPassword() Returns the current record's "password" value
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method string              getApellido() Returns the current record's "apellido" value
 * @method string              getCedula()   Returns the current record's "cedula" value
 * @method string              getRole()     Returns the current record's "role" value
 * @method Doctrine_Collection getDoctor()   Returns the current record's "Doctor" collection
 * @method Doctrine_Collection getPaciente() Returns the current record's "Paciente" collection
 * @method User                setId()       Sets the current record's "id" value
 * @method User                setUsername() Sets the current record's "username" value
 * @method User                setPassword() Sets the current record's "password" value
 * @method User                setNombre()   Sets the current record's "nombre" value
 * @method User                setApellido() Sets the current record's "apellido" value
 * @method User                setCedula()   Sets the current record's "cedula" value
 * @method User                setRole()     Sets the current record's "role" value
 * @method User                setDoctor()   Sets the current record's "Doctor" collection
 * @method User                setPaciente() Sets the current record's "Paciente" collection
 * 
 * @package    medicalagenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('apellido', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cedula', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('role', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('unique_name', array(
             'fields' => 
             array(
              0 => 'cedula',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Doctor', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Paciente', array(
             'local' => 'id',
             'foreign' => 'user_id'));
    }
}