<?php

/**
 * BaseCitaMedica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $paciente_id
 * @property integer $doctor_id
 * @property date $fecha
 * @property Paciente $Paciente
 * @property Doctor $Medico
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method integer    getPacienteId()  Returns the current record's "paciente_id" value
 * @method integer    getDoctorId()    Returns the current record's "doctor_id" value
 * @method date       getFecha()       Returns the current record's "fecha" value
 * @method Paciente   getPaciente()    Returns the current record's "Paciente" value
 * @method Doctor     getMedico()      Returns the current record's "Medico" value
 * @method CitaMedica setId()          Sets the current record's "id" value
 * @method CitaMedica setPacienteId()  Sets the current record's "paciente_id" value
 * @method CitaMedica setDoctorId()    Sets the current record's "doctor_id" value
 * @method CitaMedica setFecha()       Sets the current record's "fecha" value
 * @method CitaMedica setPaciente()    Sets the current record's "Paciente" value
 * @method CitaMedica setMedico()      Sets the current record's "Medico" value
 * 
 * @package    medicalagenda
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCitaMedica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cita_medica');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('paciente_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('doctor_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Paciente', array(
             'local' => 'paciente_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Doctor as Medico', array(
             'local' => 'doctor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}