<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2023/09/17 00:57:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=medicalagenda',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
