<?php
// auto-generated by sfSecurityConfigHandler
// date: 2023/09/17 12:48:15
$this->security = array (
  'auth' => 
  array (
    'class' => 'sfBasicSecurityFilter',
    'param' => 
    array (
      'is_enabled' => true,
      'login_module' => 'login',
      'login_action' => 'index',
    ),
  ),
  'all' => 
  array (
  ),
);
